#!/usr/bin/env python3
"""Render the frozen Study 09 mature-session audit."""

from __future__ import annotations

import json
from pathlib import Path


HERE = Path(__file__).resolve().parent
INPUT = HERE / "maturity_audit.json"
OUTPUT = HERE / "reports" / "r5-maturity-audit.md"


def fmt_count(value: int | None) -> str:
    return "—" if value is None else f"{value:,}"


def counts(record: dict[str, object] | None) -> str:
    if record is None:
        return "Excluded"
    held_out = record.get("held_out_trials")
    trial_key = "valid_trials" if record.get("valid_trials") is not None else "source_trials"
    trial_label = "trials" if trial_key == "valid_trials" else "source trials"
    base = (
        f"{fmt_count(record.get('subjects'))} subjects; "
        f"{fmt_count(record.get('sessions'))} sessions; "
        f"{fmt_count(record.get(trial_key))} {trial_label}"
    )
    if held_out is not None:
        base += f"; {fmt_count(held_out)} held out"
    return base


def render() -> str:
    audit = json.loads(INPUT.read_text())
    datasets = audit["datasets"]
    decisions = [item["decision"] for item in datasets]
    assert len(datasets) == audit["summary"]["cohorts_audited"]
    assert len({item["dataset"] for item in datasets}) == len(datasets)
    assert decisions.count("eligible unchanged") == audit["summary"]["eligible_unchanged"]
    assert decisions.count("adapter change required") == audit["summary"]["adapter_change_required"]
    assert decisions.count("exclude from mature-primary") == audit["summary"]["excluded_from_mature_primary"]
    rows = []
    for item in datasets:
        evidence = f"[{item['evidence']}]({item['source']})"
        rows.append(
            "| {label} | {evidence} | {confidence} | {decision} | {before} | "
            "{after} | {results} |".format(
                label=item["label"],
                evidence=evidence,
                confidence=item["confidence"],
                decision=item["decision"],
                before=counts(item["before"]),
                after=counts(item["after"]),
                results=item["existing_results"],
            )
        )

    detail = []
    for item in datasets:
        detail.extend(
            [
                f"### {item['label']}",
                "",
                f"**Decision:** {item['decision']} (confidence: {item['confidence']}; "
                f"evidence level {item['evidence_level']}).",
                "",
                f"**Rule:** {item['rule']}",
                "",
                f"**Evidence:** [{item['evidence']}]({item['source']})",
                "",
            ]
        )

    hierarchy = "\n".join(
        f"{index}. {item}"
        for index, item in enumerate(audit["evidence_hierarchy"], start=1)
    )
    guardrails = "\n".join(f"- {item}" for item in audit["guardrails"])
    summary = audit["summary"]
    return f"""---
id: r5
slug: maturity-audit
status: live
authors: [han, codex]
issue: {audit['issue']}
wandb_groups: []
inputs:
  scripts:
    - analysis/report_maturity_audit.py
  data:
    - analysis/maturity_audit.json
reproduce: make -C studies/09-gru-cross-species-transfer r5
---

# Result 5 — mature-session eligibility audit

This is the prespecified decision gate before any mature-only reruns. The target
estimand is: **{audit['estimand']}** No threshold in this report was selected from
GRU, common-Q, or author-model performance.

<!-- BEGIN result-5 -->
[regenerated by `analysis/report_maturity_audit.py` — do not edit by hand]

## Decision

All {summary['cohorts_audited']} admitted external cohorts were audited against their
papers and released metadata. Eleven are maturity-eligible without changing their
current canonical sample. Kwak (mouse) requires a DMSO-only adapter and complete rerun.
Miller (rat) has no defensible prespecified maturity boundary, and Alsiö (rat) measures
drug-administered acquisition/reversal rather than repeated samples of one stable
policy; both leave the mature-primary analysis.

No model job was launched during this audit. Existing Miller (rat) and Alsiö (rat)
outputs remain available only as clearly labeled sensitivity/descriptive results.

## Evidence hierarchy

{hierarchy}

## Guardrails

{guardrails}

## Cohort-level disposition

| Cohort | Prespecified evidence | Confidence | Decision | Before audit | After audit | Existing result handling |
|---|---|---|---|---|---|---|
{chr(10).join(rows)}

## Exact adapter consequence

Kwak (mouse) currently has 39 mice, each with ten DMSO and ten CNO sessions. The
generic lexical v1 split put CNO sessions into adaptation and DMSO sessions into test,
which changes treatment at the boundary. Filtering first to DMSO retains 390 sessions
and 60,045 trials. Chronological odd DMSO sessions then provide 30,170 adaptation
trials; chronological even DMSO sessions provide 29,875 immutable held-out trials.
All existing Kwak (mouse) likelihoods and embeddings remain quarantined until that
adapter, split manifest, common-Q fit, E4 transfer, and E8 transfer are regenerated.

## Important interpretation decisions

- Zid (human) keeps all 258 main-task participants, including four constant-choice
  participants whom the paper omitted from model-based analyses. They passed the
  prespecified task-understanding screen, and removing hard-to-fit behavior would
  change the predictive estimand.
- Tang (macaque) retains within-block learning and reversal. Those dynamics are the
  mature task, not pretraining; the cohort remains descriptive because it has two
  subjects.
- Costa (macaque) is mature-eligible because lesion group is fixed between subjects,
  so adaptation and test never cross treatment. It remains a stress-test cohort.
- Eckstein (human) is post-tutorial, but the public release has 306 valid files while
  the paper reports 291 analytic participants. The existing analysis continues to
  expose that discrepancy instead of guessing an exclusion list.
- Hattori (mouse) already implements the strongest available rule: session position
  15 onward, applied before chronological reindexing and splitting.

## Per-cohort evidence and rule

{chr(10).join(detail)}
## Next authorized work

1. Implement and contract-test the DMSO-only Kwak (mouse) adapter and manifest.
2. Remove Miller (rat) and Alsiö (rat) from mature-primary report panels while retaining
   labeled sensitivity panels.
3. Show the changed subject/session/trial counts in Results 1–4.
4. Only then run Kwak (mouse): common Q on HPC CPU, one E4/E8 D=614 smoke on Beaker
   GPU, followed by the full approved GPU matrix. No CPU-only work goes to Beaker.

<!-- END result-5 -->
"""


def main() -> None:
    OUTPUT.write_text(render())
    print(OUTPUT)


if __name__ == "__main__":
    main()
